version: '3'
services:
  mysql000level2:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    platform: linux/x86_64
    networks:
      - level000net2
    volumes:
      - mysql000vol2:/var/lib/mysql
      - ./DB:/tmp
      - ./mysql/my.cnf:/etc/my.cnf
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${USERPASS}
  apa000level2:
    image: httpd
    depends_on:
      - php000level2
    networks:
      - level000net2
    volumes:
      - apa000vol2:/usr/local/apache2/htdocs/
    ports:
      - "8080:80"
  php000level2:
    build: 
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - mysql000level2
    networks:
      - level000net2
    volumes:
      - ~/dockers/com_folder2/level:/var/www/html
    ports:
      - "8090:80"
    restart: always
networks:
  level000net2:
volumes:
  mysql000vol2:
  apa000vol2:
